load('chanlocs16.mat');
topo.ELEC.XYZ = [chanlocs16.X; chanlocs16.Y; chanlocs16.Z]';
topo.Label = [{chanlocs16.labels}]';
[s1,h1]=sload('MITrainingCorrect/CR09NA/S2/ALB.20111207.000000.online.mi.mi_rhbf.gdf');
[s2,h2]=sload('MITrainingCorrect/CR09NA/S2/ALB.20111207.154459.online.mi.mi_rhbf.gdf');
[s3,h3]=sload('MITrainingCorrect/CR09NA/S2/ALB.20111207.160937.online.mi.mi_rhbf.gdf');
[s4,h4]=sload('MITrainingCorrect/CR09NA/S2/ALB.20111207.171811.online.mi.mi_rhbf.gdf');
h = [h1; h2; h3; h4];% h5];
s_1 = struct('s',s1); s_2 = struct('s',s2);s_3 = struct('s',s3);s_4 = struct('s',s4);%s_5 = struct('s',s5);
s = [s_1;s_2;s_3; s_4];% s_5];
fs = h1.EVENT.SampleRate;
[lh, rh, bf] = separateTYP(h, s, true);
Hd = fildes;
[lhsamples, rhsamples] = getsamples(bf, rh, fs, Hd.Numerator);
[lhfreqsamples, rhfreqsamples] = getfreqSamplesfft(lhsamples, rhsamples, fs);
[X,Y] = getXYMatrix(lhfreqsamples, rhfreqsamples);
fisher = fsFisher(X, Y);
[A,B] = getGrandAverageMatrices(lhsamples, rhsamples);
%[ranking,a] = spider_wrapper(X,Y,592,'fisher');
%rf.fList = a.rank;
%rf.W = a.w;
%plotTopFeatures(rf);
plotTopFeatures(fisher);
plotGrandAverages(fisher, A, B);
%plotGrandAverages3(fisher, lhsamples, rhsamples, topo);